TASKS 26 52 & 58 (#70)
* Init commit

* simple comments added to data,flat, transaction etc.

* basic methods and fields sketches created.

* Loading of CSV file
Loading of user transaction

* Revert "Loading of CSV file"

This reverts commit e494c787745713163bb37545bd6fcddcfde592ea.

* Revert "basic methods and fields sketches created."

This reverts commit 965e938c94b661e41959bc342efc4ab6c1df0017.

* Revert "simple comments added to data,flat, transaction etc."

This reverts commit 87072cf0426ede0c4788203e7a97239aa403d9b2.

* Revert "Init commit"

This reverts commit 57dd148ea9b4e1b5cbf5af39cf14af70612cd8c4.

* JD5JB-9 Add filterData method

* Add FilterTransactions class filtermethods extracted

* Add enum clases and next filter methods

* JD5JB-9 Add cheapest and most expensive transaction validation

* add removeInvalidTransaction method, FilterSelector method WiP

* Add selectorFilter recursive method and theGreatFatFilter method - untested

* minor code refactoring

* added trim to district, corrected view in transaction, corrected view in options menu

* JD5JB-9 Cheapest and MostExpensive transaction methods refactored

* added algorithm properties

* JD5JB-9 isXLevel and isXFlatArea methods converted to filters

* JD5JB-9remove invalid transactions method reconstruted

* JD5JB-9 Add Parameters from config file

* added clean screen and properties contain default values for filters

* JD5JB-9 Add IgnoreCase to basicFilter Method 0 size list bug resolved in removeOutliers method

* I hope it works

* JD5JB-9removeOutliers method too small list input error repaired

* JD5JB-9remove comments

* JD5JB-9remove unused classes

* Add ConsolViewer Class containing clearScreen() method, small refactoring in Other classes

* Fixed updatePrice bug

* Added weight factor for counting final price per m2

* Completed calculatePrice
Prevents to calculatePrice if filteredList < 11

* Edited few regex

* MultiDistrict filter acitvated

* correction of text and app presentation in terminal

* MultiDistrict filter acitvated

* JD5JB-9 add early stop after basic filter small result list at selectorFilter method

* JD5JB-9 Add CalculatePrice class - feature completed

* first try with servlets

* JD5JB-7 Add first test to class DistrWagesHandler

* add view home and new-transaction

* add utf-8 and part footer, header

* 1st try with web

* modify logger

* add servlet and template new transaction

* add options list of form new-transaction

* JD5JB-7 WiP resolving problems with remove outliers modified method

* upload file feature

* JD5JB-7Remove Outliers method upgreaded tests added

* new user-trannsactions servlet with creating table from file

* added wycen button next to each row
improved visual look of table with datatable.net

* be4 merge with Tomek's branch

* After merge

* After merge

* adding flats to file feature

* adding flats to file feature
fix for UTF-8 encoding

* Added few fixes from pull request
LOGS
Exceptions
Added valuation of price, if 0 then cannot perform valuation

* JD5JB-7 bug in DistrWagesHandler -> FilterTransactions fixed

* JD5JB-7 districtWageHandler and it's implementations refactored

* JD5JB-7 problems with resource files paths resolved

* JD5Jb-7 fixed FilePaths to transaction.csv, app.properties and districts. properties - actual file source folder is: jar's resources folder

* JD5Jb-7 fixed FilePaths to transaction.csv, app.properties and districts. properties - actual file source folder is: jar's resources folder

* JD5JB-7 up to date with develop

* add raport

* Add table to raport.pdf

* JD5JB-7generating Report WiP

* JD5JB-7 add line under title, polish font and watermark to report

* Add content to pdf w-i-p

* Add methods to StatisticsManager - getting specific statistics

* JD5JB-7 Add write pdf content

* JD5JB-7 minor changes in pdf content

* JD5JB-7 file structure cleaned

* JD5JB-7 file structure cleaned (#25)

* JD5JB-30 SonarQube changes applied

* JD5JB-30 SonarQube - more changes applied

* JD5JB-30 minor changes to pdf creation

* Add StaticFields Singleton class

* JD5JB30_a Add StaticFields singleton class

* JD5JB-52/58_df-stat-fix Local decimal format differences fixed, StaticFields singleton class added

* bugs fixed

* properties tables addes to .sql file

* added tables config and district_properties to database

* .sql file edited

* use database data in app w-i-p

* wip

* wip

* new table added to database ne entities added to app module

* connection to database acquired

* StaticFields class generate error java.lang.NoClassDefFoundError

* configuration from database w-i-p - first success

* added new Config table w-i-p

* added new table districts_wages todo use table config instead of properties in whole app

* w i p

* Filterstranscripted to use database

* cleaning project structure to fully use new tranzaction class

* city/ district selecton based on database achived - errors in valuationprocess

* valuation performed correctly for single district - multi district filter in progress

* All filter options activated properly

*  minor changes in project structure

* tasks 26/52/58 completed

* unused sql files deleted